// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilhtazxquukyfbiiuwne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsaHRhenhxdXVreWZiaWl1d25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTM2NjksImV4cCI6MjA2OTUyOTY2OX0.EIZiJrmWlctqzEeLcu1yF606Nrp6Ny2CFtaNDPTcWTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});